
  CREATE TABLE "SCOTT"."DIVTBL" 
   (	"DIVISION" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"NAMES" VARCHAR2(120 BYTE), 
	 CONSTRAINT "DIVTBL_PK" PRIMARY KEY ("DIVISION")
   ) ;
  
  
  CREATE TABLE "SCOTT"."BOOKSTBL" 
   (	"IDX" NUMBER(*,0) NOT NULL ENABLE, 
	"AUTHOR" VARCHAR2(300 BYTE), 
	"DIVISION" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"NAMES" VARCHAR2(900 BYTE) NOT NULL ENABLE, 
	"RELEASEDATE" DATE, 
	"ISBN" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	 CONSTRAINT "BOOKSTBL_PK" PRIMARY KEY ("IDX"), 
	 CONSTRAINT "FK_DIVISION" FOREIGN KEY ("DIVISION")
	  REFERENCES "SCOTT"."DIVTBL" ("DIVISION") ENABLE
   ) ;


	CREATE TABLE "SCOTT"."MEMBERTBL" 
   (	"IDX" NUMBER(*,0) NOT NULL ENABLE, 
	"NAMES" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"LEVELS" CHAR(1 BYTE), 
	"ADDR" VARCHAR2(300 BYTE), 
	"MOBILE" VARCHAR2(13 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"USERID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"LASTLOGINDT" DATE, 
	"LOGINIPADDR" VARCHAR2(30 BYTE), 
	 CONSTRAINT "MEMBERTBL_PK" PRIMARY KEY ("IDX")
	);
	
	CREATE TABLE "SCOTT"."RENTALTBL" 
   (	"IDX" NUMBER(*,0) NOT NULL ENABLE, 
	"MEMBERIDX" NUMBER(*,0), 
	"BOOKIDX" NUMBER(*,0), 
	"RENTALDATE" DATE, 
	"RETURNDATE" DATE, 
	 CONSTRAINT "RETALTBL_PK" PRIMARY KEY ("IDX"),
	 CONSTRAINT "FK_BOOKIDX" FOREIGN KEY ("BOOKIDX")
	  REFERENCES "SCOTT"."BOOKSTBL" ("IDX") ENABLE, 
	 CONSTRAINT "FK_MEMBERIDX" FOREIGN KEY ("MEMBERIDX")
	  REFERENCES "SCOTT"."MEMBERTBL" ("IDX") ENABLE
	);
